id: P002998
initial_creation_type: ocr
source_metadata:
  id: bdr:W25127
  title: ནད་རིགས་སྣ་ཚོགས་ཀྱི་མངོན་རྟགས་དང་བཅོས་ཐབས་བཤད་པ་རབ་གསལ་སྒྱུ་འཕྲུལ་མེ་ལོང
  author: ''
  volumes:
    90a9d270e8e04ddab01f6490f64d7e69:
      image_group_id: I5051
      title: ''
      volume_number: 1
      total_pages: 326
